## try throw catch 实现异常的检测抛出捕获
```cpp
#include<iostream>
#include<cstring>
using namespace std;
class MyString
{
public:
    MyString(const char*s=""){_s=new char[strlen(s)+1];strcpy(_s,s);}
    ~MyString(){delete[] _s;}
    friend ostream&operator<<(ostream& o,const MyString& other);
    char& operator[](int index)
    {
    if(index<0||index>=strlen(_s))throw out_of_range("下标越界");
    return _s[index];
    }
private:
    char*_s;
};
ostream& operator<<(ostream& o, const MyString& other)
{
    o << "\"" << other._s << "\"";//前面加转义字符'\'，输出双引号
    return o;
}
int main()
{
    MyString str("abc");
    cout<<str<<endl;
    try{//检测
        str[3]='C';
        cout<<str<<endl;
    }
    catch(exception&e)//根基类exception
    {//捕获
        cout<<e.what()<<endl;
    }
    cin.get();
    return 0;
}
```